# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55290874f109ed9ab3ff3bd31f978681"
name = "syatt-fulfillment"
application_url = "https://changelog-themes-firefox-videos.trycloudflare.com"
embedded = true
handle = "syatt-fulfillment"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_orders,read_shipping,write_shipping,write_delivery_customizations,read_locations"

[auth]
redirect_urls = ["https://changelog-themes-firefox-videos.trycloudflare.com/auth/callback", "https://changelog-themes-firefox-videos.trycloudflare.com/auth/shopify/callback", "https://changelog-themes-firefox-videos.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
